# Uncomment the next line to define a global platform for your project
# platform :ios, '13.3'

target 'recipeplus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!
  # Pods for recipeplus

  target 'recipeplusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'recipeplusUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'RealmSwift'

end
